### PR TITLE
Internationalization support

### PR DESCRIPTION
**Pull request by marlonpatrick10**
Adjustments to internationalize the theme: formatting dates, messages, labels, sidebar etc.

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
So sweet man! i'm currently check your code :)

**Comment by LouisBarranqueiro** [comment]
Does Hexo create the respective folder for english and portuguese languages? I have Hexo 3.1.1 and folders are not generated

**Comment by marlonpatrick10** [comment]
Louis, I not commit any changes related to the dual language blog, I sent just adjustments related to internationalization.

Thus, the user can download your theme and specify things like the date format, labels of a few buttons and links and adapt it the language of your choice. However, it still remains mono language.

**Comment by LouisBarranqueiro** [comment]
oh ok.  I thought that Hexo will generate all posts with a blog in english in /en and in Portuguese in /pt-br. I have improved label file structure and reduce its length. Tell me what do you think. i worked on PR/66 branch. Create a new PR with this branch if you are ok with modifications or add more commits :)

**Comment by marlonpatrick10** [comment]
Louis, your adjustments were great. For me, it's ok.

**Comment by LouisBarranqueiro** [comment]
Create new PR from branch PR66 please :)

**Comment by LouisBarranqueiro** [comment]
I don't know when you will be back so I will do it to release the theme now :)

**Pull request merged**
