### PR TITLE
Dev - twitter card support

### PR DESCRIPTION
**Pull request by zoharsacks**

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
Thank you man for your explanations about twitter card. I checked twitter card docs too. Before accepting pull request please do this :  
1. In `_config.yml`, use `twitter` instead of `twitter_handle` variable, and place it in `author` variable with email, bio, etc. it's more appropriate than integrated services.  
2. Rename `social` folder in `head` to locate all partial files integrated in head tag more easily.  
3. Like you did for for post excerpt, please do the same with images. First, check if cover image (`coverImage`) exists, after thumbnail image (`thumbnailImage`) and finally photos (`photos`)

**Comment by zoharsacks** [comment]
#33 suggests using OG helper.
OG covers twitter card as well
I suggest closing both #33 and #37 (this pull request) and write a comprehensive solution (when I say write I mean I can write it :)) @jigsawye what do you think?

**Comment by jigsawye** [comment]
@zoharsacks I can't agree more :)

**Comment by LouisBarranqueiro** [comment]
i'm waiting your work :)

**Comment by zoharsacks** [comment]
closed

**Pull request closed without merging**
