### PR TITLE
Post comment enabled or not judgement support.

### PR DESCRIPTION
**Pull request by h404bi**
**How to use:**
To disable the comment of a post/page, the front-matter should add `comments: false`:
```
title: ...
date: ...
comments: false
---
```

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
yes, good idea. Could you just put in one line like `if (post.comment && config.disqus_shortname) {` please. It's more readable and easy to understand

**Comment by h404bi** [comment]
Done. ~

**Comment by LouisBarranqueiro** [comment]
Perfect! :) Please remove the gitignore file.

**Comment by h404bi** [comment]
Ok, if you don't want the gitignore file.

**Comment by LouisBarranqueiro** [comment]
Yes, because each person have different OS and IDE. Like this, each person can configure his own .gitignore without having a file to commit. Thank you. You are the second contributor :)

**Pull request merged**
