### PR TITLE
Adds fa-list icon as scroll to top button next to social buttons - Same as #43 but to dev

### PR DESCRIPTION
**Pull request by justincalleja**
PR for #41

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
Sweet :). I will merge this PR just after I had finished to implement the share button feature.

**Comment by justincalleja** [comment]
:+1:

**Comment by LouisBarranqueiro** [comment]
@justincalleja  I just added the other feature. here is the result :)
**on small screen :**

on small screen
  
**on very small screen :**

on very small screen closed
   
**on very small screen (opened) :**
on very small screen opened

**Comment by justincalleja** [comment]
Well done Louis! I haven't tried it out yet but will soon :)

Merci beaucoup!

**Comment by justincalleja** [comment]
Tried it out btw, nice job :+1:

**Pull request merged**
