### PR TITLE
Use font-family scss variable

### PR DESCRIPTION
**Pull request by juampi92**
Hi! I wanted to change the default font family, so I figured this way it's easier to replace on the entire theme. I hope it helps. Awesome theme btw.

### CODE REVIEW

**Comment by LouisBarranqueiro** [comment]
It's a good idea but you implementation is a bit brutal. I will commit soon on this PR to improve this implementation.

**Comment by kaedea** [comment]
Now I manually edit the font in scss. The default font of the release version 1.3.0 is not good for Chiese and Japanese Character. It is good to make this configurable in the theme `_config.yml`, I think. If you want to add `Chiese and Japanese Font` support, I can help to choose fonts and show you the effect.

**Comment by h404bi** [comment]
This is useful, for users can change font easier. Besides, font of code block looks awful.
code

**Comment by LouisBarranqueiro** [comment]
Check #115 , I add some improvements

**Pull request closed without merging**
