### PR TITLE
Added _config.yml option to exclude self from Google Analytics

### PR DESCRIPTION
**Pull request by justincalleja**
Based on http://tjvantoll.com/2012/08/28/google-analytics-excluding-visits-in-development-and-production/

Have not tested the query parameters analytics=on, analytics=off - only tried in localhost. But seems like it should work. Will be testing when blog goes live.

### CODE REVIEW

**Comment by justincalleja** [comment]
Update: have now tested the query params locally using IP address and... well there was a bug :)

now it's fixed.

**Comment by LouisBarranqueiro** [comment]
It's an interesting feature but it complicated a lot the code for something that you can do more easily on Google Analytics website by adding a filter with `(.*?localhost.*?)`. This is what I did for my own blog.

**Comment by justincalleja** [comment]
hmm... ok fair enough ^^;

I will still use this approach for my blog as I'm not too familiar with Google Analytics, and this way is guaranteed not to track me.

Another advantage is that I (well, as well as other users if they know about it), can opt out of tracking when the site is deployed (via query params + localStorage).

But yes, agreed. It is a bit long with regards code maintenance. With regards code download, `google_analytics_exclude_self` is disabled by default and produces the same code as before (just the Google Analytics script).

Your project, your call :)

**Comment by LouisBarranqueiro** [comment]
It complicated the code and the user experience I think. I want a theme highly connected but easy to use. The theme allow users to integrate some useful services like Google analytics, Disqus, swiftype, gravatar but I don't want to add features to configure these services, I prefer to let users configure each services on their respective websites.

I will add in user documentation a short tutorial on how to add filter on Google Analytics to exclude localhost.  

I really appreciate your contribution and your involvement. If you have new services that can be useful for the theme, don't hesitate :)

**Comment by justin-calleja** [comment]
Cool I understand :+1: 

I do have something which I'll try getting round to. Take a look at this: http://justincalleja.com/blog/marionette-compositeview-an-example/

It's a bit long and a table of contents or something which helps navigation is, I think, necessary.

Do you think something like the table of contents at the top of the page on the right is appropriate for this theme? Or maybe some way to opt in and out of it (_config.yaml wise or per .md file)? Or do you think there are better approaches to help with navigation?

Also, was planning on adding some way of scrolling to the top (like the jquery-scrollUp plugin used on that blog... it's just that I don't know whether the current look of it will jar with the theme - I'm no good at design ^^;)

Cheers!

**Comment by LouisBarranqueiro** [comment]
Yes, it a good idea. Create an issue to talk about and plan this new features :)

**Pull request closed without merging**
